/**
 * fotos-data.js — Lista estática de todas las imágenes/vídeos de la galería.
 * Rutas relativas al HTML (sin / al inicio) para que funcionen en Netlify y móvil.
 * Actualizado: 20/02/2026 — Incluye fotos de photos/FOOD, Bread, DRINKS, SWEET.
 */
var FOTOS_DATA = [
  // —— SWEET (dulces) ——
  { src: "photos/SWEET/WhatsApp Video 2026-02-19 at 17.30.074.mp4", categoria: "sweet", nombre: "Video dulces", isVideo: true },
  { src: "photos/SWEET/WhatsApp Image 2026-02-19 at 00.jpeg", categoria: "sweet", nombre: "Cheesecake pistacho" },
  { src: "photos/SWEET/WhatsApp Image 2026-02-19 at 17.30.07.jpeg", categoria: "sweet", nombre: "Baklava redondo" },
  { src: "photos/SWEET/WhatsApp Image 2026-02-19 at 17.30.085.jpeg", categoria: "sweet", nombre: "Baklava cheesecake" },
  { src: "photos/SWEET/WhatsApp Image 2026-02-19 at 17.30.086.jpeg", categoria: "sweet", nombre: "Baklava porción" },
  { src: "photos/SWEET/WhatsApp Image 2026-02-19 at 17.30.087.jpeg", categoria: "sweet", nombre: "Pasteles pistacho" },
  { src: "photos/SWEET/WhatsApp Image 2026-02-19 at 17.30.088.jpeg", categoria: "sweet", nombre: "Tarta pistacho" },
  { src: "photos/SWEET/WhatsApp Image 2026-02-19 at 17.30.090.jpeg", categoria: "sweet", nombre: "Vitrina dulces" },
  { src: "photos/SWEET/WhatsApp Image 2026-02-19 at 17.30.099.jpeg", categoria: "sweet", nombre: "Dulces pistacho" },
  { src: "photos/SWEET/WhatsApp Image 2026-02-19 at 173.30.07.jpeg", categoria: "sweet", nombre: "Baklava capas" },
  { src: "photos/SWEET/2.jpeg", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/2.jpg", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/4.jpg", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/15.jpg", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/SKELET.webp", categoria: "sweet", nombre: "Skeleton" },
  { src: "photos/SWEET/Chocolats 1 beige.jpg", categoria: "sweet", nombre: "Chocolats" },
  { src: "photos/SWEET/Chocolats beiger.jpg", categoria: "sweet", nombre: "Chocolats" },
  { src: "photos/SWEET/Croissant aux amandes beige.jpg", categoria: "sweet", nombre: "Croissant aux amandes" },
  { src: "photos/SWEET/Kinuskikakku beige.jpg", categoria: "sweet", nombre: "Kinuskikakku" },
  { src: "photos/SWEET/Leivoset 3 beige.jpg", categoria: "sweet", nombre: "Leivoset" },
  { src: "photos/SWEET/Petits pains 2.jpg", categoria: "sweet", nombre: "Petits pains" },
  { src: "photos/SWEET/Porkkana-kinuskikakku beige.jpg", categoria: "sweet", nombre: "Porkkana kinuskikakku" },
  { src: "photos/SWEET/Untitled-1.jpg", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/HCN_8344.JPG", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/HCN_8349.JPG", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/HCN_8387.JPG", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/HCN_8388.jpg", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/HCN_8391.jpg", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/HCN_8396.jpg", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/HCN_8471.jpg", categoria: "sweet", nombre: "Dulces" },
  { src: "photos/SWEET/20250627213603-6be1974d.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213604-5ee4b738.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213604-61d230a0.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213604-c70be31d.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213606-223befd0.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213606-86f0d6bc.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213607-0015c272.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213607-e5a801bc.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213607-f95346ab.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213608-f52cfa5f.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250627213609-73a2c471.png", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250702111535-9e2529f1.jpg", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250702111554-95e70287.jpg", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250702121648-f290b313.jpg", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250702121655-b1eefdd6.jpg", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250702121710-73fdcfce.jpg", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250702121715-cbff3fd2.jpg", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/20250706215231-839b0b2b.jpg", categoria: "sweet", nombre: "Sweet" },
  { src: "photos/SWEET/ABELLANA CORSSAIN.jpg", categoria: "sweet", nombre: "Abellana Corssain" },
  { src: "photos/SWEET/CAKE CHOCOLATE MADUSHA.jpg", categoria: "sweet", nombre: "Cake Chocolate Madusha" },
  { src: "photos/SWEET/CAKE MADUSHA.jpg", categoria: "sweet", nombre: "Cake Madusha" },
  { src: "photos/SWEET/celebro cake.jpg", categoria: "sweet", nombre: "Celebro cake" },
  { src: "photos/SWEET/Kakku 1.jpg", categoria: "sweet", nombre: "Kakku" },
  { src: "photos/SWEET/Kakku sarja 1 beige.jpg", categoria: "sweet", nombre: "Kakku sarja" },
  { src: "photos/SWEET/Korvapuusti beige.jpg", categoria: "sweet", nombre: "Korvapuusti" },
  { src: "photos/SWEET/Lautanen beige.jpg", categoria: "sweet", nombre: "Lautanen" },
  { src: "photos/SWEET/Leivoset 1 beige.jpg", categoria: "sweet", nombre: "Leivoset" },
  { src: "photos/SWEET/NUS CORSSAIN.jpg", categoria: "sweet", nombre: "Nus Corssain" },
  { src: "photos/SWEET/PIPAS CCON MIEL.jpg", categoria: "sweet", nombre: "Pipas con miel" },
  { src: "photos/SWEET/PISSTACH CORSSAIN.jpg", categoria: "sweet", nombre: "Pistacho Corssain" },
  { src: "photos/SWEET/Pistaasi Baklava.png", categoria: "sweet", nombre: "Pistaasi Baklava" },
  { src: "photos/SWEET/Porkkanakakku beige.jpg", categoria: "sweet", nombre: "Porkkanakakku" },
  { src: "photos/SWEET/Pähkinä Baklava.png", categoria: "sweet", nombre: "Pähkinä Baklava" },
  { src: "photos/SWEET/SWEET SUSHI.jpg", categoria: "sweet", nombre: "Sweet Sushi" },
  // —— BREAD (pan) ——
  { src: "photos/Bread/20250702110728-5f0dcbc8.jpg", categoria: "bread", nombre: "Pan" },
  { src: "photos/Bread/20250702111540-7ad99697.jpg", categoria: "bread", nombre: "Pan" },
  { src: "photos/Bread/Crakers beige.jpg", categoria: "bread", nombre: "Crakers" },
  { src: "photos/Bread/Croissant beige.jpg", categoria: "bread", nombre: "Croissant" },
  { src: "photos/Bread/Marrakech Leipä.png", categoria: "bread", nombre: "Marrakech Leipä" },
  { src: "photos/Bread/Pain rond beige.jpg", categoria: "bread", nombre: "Pain rond" },
  { src: "photos/Bread/Pains en serie beige.jpg", categoria: "bread", nombre: "Pains en serie" },
  { src: "photos/Bread/Pains fond beige.jpg", categoria: "bread", nombre: "Pains fond" },
  { src: "photos/Bread/Pains groupés avec fond gris.jpg", categoria: "bread", nombre: "Pains groupés" },
  { src: "photos/Bread/Ronds beiges.jpg", categoria: "bread", nombre: "Ronds beiges" },
  { src: "photos/Bread/Ruisleipä beige.jpg", categoria: "bread", nombre: "Ruisleipä" },
  { src: "photos/Bread/Tous les pains beige.jpg", categoria: "bread", nombre: "Tous les pains" },
  // —— DRINKS (bebidas) ——
  { src: "photos/DRINKS/u3829884585_lifestyle_image_of_espresso_at_home_--ar_21_--sty_2f05ab05-dded-4e06-ae09-e7ea15735558_2.png", categoria: "drinks", nombre: "Espresso" },
  { src: "photos/DRINKS/u3829884585_Making_coffee_with_latte_art_shaped_like_a_heart__f9fc4b4c-3bd6-44a1-97a1-007769d252e8_1.png", categoria: "drinks", nombre: "Latte" },
  { src: "photos/DRINKS/u3829884585_Product_photography_of_a_tall_glass_of_americano__7fe54362-81e4-421d-ad03-3ee71fd28f9c_0.png", categoria: "drinks", nombre: "Americano" },
  { src: "photos/DRINKS/u3829884585_Steaming_chai_tea_being_poured_into_a_transparent_d605f895-c3ce-45fb-bb9e-4291e1826c0a_0 (1).png", categoria: "drinks", nombre: "Chai" },
  // —— FOOD (comida) ——
  { src: "photos/FOOD/1.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/5.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/6.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/7.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/8.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/9.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/10.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/11.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/12.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/13.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/14.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/16.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/18.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/20.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/21.jpg", categoria: "food", nombre: "Comida" },
  { src: "photos/FOOD/Carré beige.jpg", categoria: "food", nombre: "Carré" },
  { src: "photos/FOOD/Karjalapiirakka beige.jpg", categoria: "food", nombre: "Karjalapiirakka" },
  { src: "photos/FOOD/Petits pains 3.jpg", categoria: "food", nombre: "Petits pains" },
  { src: "photos/FOOD/Petits pains 4.jpg", categoria: "food", nombre: "Petits pains" },
  { src: "photos/FOOD/Piirakat 1beige.jpg", categoria: "food", nombre: "Piirakat" },
  { src: "photos/FOOD/Piirakat 3 beige.jpg", categoria: "food", nombre: "Piirakat" },
  { src: "photos/FOOD/Ronds beiges.jpg", categoria: "food", nombre: "Ronds" },
  { src: "photos/FOOD/Triangle beige.jpg", categoria: "food", nombre: "Triangle" }
];
